spring:
  application:
    name: battle-service
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:flashcard_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9090/realms/flashcard}

server:
  port: 8084

logging:
  level:
    com.flashcard: DEBUG

